#!/usr/bin/env bash
set -euo pipefail

# Need to know where rhad root ACTUALLY lives on disk -- this looks gross, but
RHAD_ROOT="$(dirname "$(dirname "$(realpath "$(command -v rhad)")")")"
export RHAD_ROOT

# shellcheck disable=SC1091
source "${RHAD_ROOT}"/scripts/utils.sh

# Take path as first arg, but default to current dir
target="${1:-.}"

# Only run for a certain language ecosystem (useful for testing)
lang="${2:-}"

# function get-plugins() {
#   printf "Using %s for rhad plugins\n" "${RHAD_PLUGIN_DIR:=${HOME}/rhad-plugins}"
#   for plugin in "${RHAD_PLUGIN_DIR}"/*; do
#     echo "${plugin}"
#   done
# }

function rhad-lint() {
  rm -rf "${failed_lint_logfile:-}"
  # shellcheck disable=2043
  for linter in "${RHAD_ROOT}"/linters/"${lang}"* ; do
    bash "${linter}" "${target}" # || printf '%s\n' "${lang}" >> /tmp/rhad-lint-failures
  done
  if [[ -s "${failed_lint_logfile}" ]]; then
    printf "\n>>>>>>>> ERROR: rhad linting failures detected!\n" 
    exit 1
  fi
}

function main() {
  rhad-lint
}

main
