name: rhad

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  main:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
        - {os: ubuntu-latest}

    steps:
    - uses: actions/checkout@v2
    - name: Build & test
      run: make image-build
