name: rhad

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test-rhad:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: sudo bash scripts/init.sh
      - name: Test
        run: make test
